[package]
name = "brinkokevin/react-hooks"
description = "React hooks for Rodux"
authors = ["SolarHorizon"]
version = "0.3.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"

[dependencies]
React = "core-packages/react@17.0.1-rc.16"